In [ ]:
import requests
import pandas as pd

api_key = "######"  # ← kendi key’ini buraya yaz

tv_shows = []

# 10 sayfa = 200 dizi
for page in range(1, 11):
    print(f"Fetching page {page}...")
    url = f"https://api.themoviedb.org/3/tv/top_rated?api_key={api_key}&language=en-US&page={page}"
    response = requests.get(url)
    data = response.json()

    for show in data['results']:
        tv_shows.append({
            "TV Show ID": show['id'],
            "Title": show['name'],
            "Rating": show['vote_average'],
            "genre_ids": show['genre_ids'],
            "Overview": show['overview'],
            "First Air Date": show['first_air_date']
        })

# DataFrame'e çevir
tv_df = pd.DataFrame(tv_shows)

# TV dizileri için tür isimlerini çek
genre_url = f"https://api.themoviedb.org/3/genre/tv/list?api_key={api_key}&language=en-US"
genre_data = requests.get(genre_url).json()
genre_map = {genre['id']: genre['name'] for genre in genre_data['genres']}

# genre_ids → tür isimleri
tv_df['Genres'] = tv_df['genre_ids'].apply(lambda ids: [genre_map.get(i, "Unknown") for i in ids])
tv_df.drop(columns=['genre_ids'], inplace=True)

# CSV olarak kaydet
tv_df.to_csv("tmdb_top_200_tv.csv", index=False)
print("Top 200 TV dizisi başarıyla kaydedildi!")

# İlk satırları göster
tv_df.head()

Fetching page 1...
Fetching page 2...
Fetching page 3...
Fetching page 4...
Fetching page 5...
Fetching page 6...
Fetching page 7...
Fetching page 8...
Fetching page 9...
Fetching page 10...
Top 200 TV dizisi başarıyla kaydedildi!

,TV Show ID,Title,Rating,Overview,First Air Date,Genres
0,1396,Breaking Bad,8.926,"Walter White, a New Mexico chemistry teacher, ...",2008-01-20,"[Drama, Crime]"
1,219246,When Life Gives You Tangerines,8.868,"In Jeju, a spirited girl and a steadfast boy's...",2025-03-07,[Drama]
2,209867,Frieren: Beyond Journey's End,8.781,After the party of heroes defeated the Demon K...,2023-09-29,"[Animation, Action & Adventure, Sci-Fi & Fanta..."
3,94605,Arcane,8.800,Amid the stark discord of twin cities Piltover...,2021-11-06,"[Animation, Sci-Fi & Fantasy, Drama, Action & ..."
4,131378,Adventure Time: Fionna & Cake,8.758,Fionna and Cake – with the help of the former ...,2023-08-31,"[Animation, Sci-Fi & Fantasy, Action & Adventu..."

In [5]:

netflix_shows = []

for page in range(1, 11):  # ilk 10 sayfa (200 diziye kadar)
    print(f"Fetching page {page}...")
    url = (
        f"https://api.themoviedb.org/3/discover/tv"
        f"?api_key={api_key}"
        f"&language=en-US"
        f"&sort_by=vote_average.desc"
        f"&page={page}"
        f"&with_networks=213"
        f"&vote_count.gte=100"  # en az 100 oylama almış dizileri al
    )

    response = requests.get(url)
    data = response.json()

    for show in data['results']:
        netflix_shows.append({
            "TV Show ID": show['id'],
            "Title": show['name'],
            "Rating": show['vote_average'],
            "genre_ids": show['genre_ids'],
            "Overview": show['overview'],
            "First Air Date": show['first_air_date']
        })

# DataFrame oluştur
netflix_df = pd.DataFrame(netflix_shows)

# Tür ID'lerini isimlere çevirelim
genre_url = f"https://api.themoviedb.org/3/genre/tv/list?api_key={api_key}&language=en-US"
genre_data = requests.get(genre_url).json()
genre_map = {genre['id']: genre['name'] for genre in genre_data['genres']}

# genre_ids → isim
netflix_df['Genres'] = netflix_df['genre_ids'].apply(lambda ids: [genre_map.get(i, "Unknown") for i in ids])
netflix_df.drop(columns=['genre_ids'], inplace=True)

# CSV olarak kaydet
netflix_df.to_csv("netflix_top_200_tv.csv", index=False)
print("Netflix dizileri kaydedildi!")

netflix_df.head()

Fetching page 1...
Fetching page 2...
Fetching page 3...
Fetching page 4...
Fetching page 5...
Fetching page 6...
Fetching page 7...
Fetching page 8...
Fetching page 9...
Fetching page 10...
Netflix dizileri kaydedildi!

,TV Show ID,Title,Rating,Overview,First Air Date,Genres
0,219246,When Life Gives You Tangerines,8.868,"In Jeju, a spirited girl and a steadfast boy's...",2025-03-07,[Drama]
1,94605,Arcane,8.800,Amid the stark discord of twin cities Piltover...,2021-11-06,"[Animation, Sci-Fi & Fantasy, Drama, Action & ..."
2,66732,Stranger Things,8.596,"When a young boy vanishes, a small town uncove...",2016-07-15,"[Drama, Sci-Fi & Fantasy, Mystery]"
3,124834,Heartstopper,8.588,Teens Charlie and Nick discover their unlikely...,2022-04-22,[Drama]
4,61222,BoJack Horseman,8.547,Meet the most beloved sitcom horse of the '90s...,2014-08-22,"[Animation, Comedy, Drama]"

In [7]:

disney_shows = []

for page in range(1, 11):  # 10 sayfa = 200 dizi
    print(f"Fetching page {page}...")
    url = (
        f"https://api.themoviedb.org/3/discover/tv"
        f"?api_key={api_key}"
        f"&language=en-US"
        f"&sort_by=vote_average.desc"
        f"&page={page}"
        f"&with_networks=2739"
        f"&vote_count.gte=100"  # az oy almış çöpler filtrelensin
    )

    response = requests.get(url)
    data = response.json()

    for show in data['results']:
        disney_shows.append({
            "TV Show ID": show['id'],
            "Title": show['name'],
            "Rating": show['vote_average'],
            "genre_ids": show['genre_ids'],
            "Overview": show['overview'],
            "First Air Date": show['first_air_date']
        })

# DataFrame oluştur
disney_df = pd.DataFrame(disney_shows)

# Tür ID'lerini isimlere çevirmek için:
genre_url = f"https://api.themoviedb.org/3/genre/tv/list?api_key={api_key}&language=en-US"
genre_data = requests.get(genre_url).json()
genre_map = {genre['id']: genre['name'] for genre in genre_data['genres']}

# genre_ids → genre isimleri
disney_df['Genres'] = disney_df['genre_ids'].apply(lambda ids: [genre_map.get(i, "Unknown") for i in ids])
disney_df.drop(columns=['genre_ids'], inplace=True)

# CSV'ye yaz
disney_df.to_csv("disneyplus_top_200_tv.csv", index=False)
print("Disney+ dizileri başarıyla kaydedildi!")

disney_df.head()

Fetching page 1...
Fetching page 2...
Fetching page 3...
Fetching page 4...
Fetching page 5...
Fetching page 6...
Fetching page 7...
Fetching page 8...
Fetching page 9...
Fetching page 10...
Disney+ dizileri başarıyla kaydedildi!

,TV Show ID,Title,Rating,Overview,First Air Date,Genres
0,97186,"Love, Victor",8.600,Victor is a new student at Creekwood High Scho...,2020-06-17,"[Comedy, Drama]"
1,36189,Boris,8.583,Boris is an Italian television series created ...,2007-04-16,[Comedy]
2,138502,X-Men '97,8.547,"The X-Men, a band of mutants who use their unc...",2024-03-20,"[Animation, Action & Adventure, Sci-Fi & Fantasy]"
3,4194,Star Wars: The Clone Wars,8.459,"Yoda, Obi-Wan Kenobi, Anakin Skywalker, Mace W...",2008-10-03,"[Action & Adventure, Sci-Fi & Fantasy, Animation]"
4,126485,Moving,8.500,"Children who live in hiding with superpowers, ...",2023-08-09,"[Mystery, Drama, Action & Adventure]"

In [9]:

prime_shows = []

for page in range(1, 11):  # 10 sayfa = 200 diziye kadar
    print(f"Fetching page {page}...")
    url = (
        f"https://api.themoviedb.org/3/discover/tv"
        f"?api_key={api_key}"
        f"&language=en-US"
        f"&sort_by=vote_average.desc"
        f"&page={page}"
        f"&with_networks=1024"
        f"&vote_count.gte=100"
    )

    response = requests.get(url)
    data = response.json()

    for show in data['results']:
        prime_shows.append({
            "TV Show ID": show['id'],
            "Title": show['name'],
            "Rating": show['vote_average'],
            "genre_ids": show['genre_ids'],
            "Overview": show['overview'],
            "First Air Date": show['first_air_date']
        })

# DataFrame oluştur
prime_df = pd.DataFrame(prime_shows)

# Tür adlarını çek
genre_url = f"https://api.themoviedb.org/3/genre/tv/list?api_key={api_key}&language=en-US"
genre_data = requests.get(genre_url).json()
genre_map = {genre['id']: genre['name'] for genre in genre_data['genres']}

# ID'leri tür isimlerine çevir
prime_df['Genres'] = prime_df['genre_ids'].apply(lambda ids: [genre_map.get(i, "Unknown") for i in ids])
prime_df.drop(columns=['genre_ids'], inplace=True)

# CSV'ye kaydet
prime_df.to_csv("primevideo_top_tv.csv", index=False)
print("Prime Video dizileri başarıyla kaydedildi!")

prime_df.head()

Fetching page 1...
Fetching page 2...
Fetching page 3...
Fetching page 4...
Fetching page 5...
Fetching page 6...
Fetching page 7...
Fetching page 8...
Fetching page 9...
Fetching page 10...
Prime Video dizileri başarıyla kaydedildi!

,TV Show ID,Title,Rating,Overview,First Air Date,Genres
0,94954,Hazbin Hotel,8.700,In attempt to find a non-violent alternative f...,2024-01-18,"[Animation, Comedy, Sci-Fi & Fantasy, Action &..."
1,85077,The Chosen,8.643,The life of Christ through the eyes of those w...,2019-04-21,"[Drama, Family, Action & Adventure]"
2,95557,INVINCIBLE,8.639,Mark Grayson is a normal teenager except for t...,2021-03-25,"[Animation, Sci-Fi & Fantasy, Action & Adventu..."
3,259666,No One Will Miss Us,8.633,"It's the '90s, and five losers run an illegal ...",2024-08-09,"[Drama, Comedy]"
4,76479,The Boys,8.459,A group of vigilantes known informally as “The...,2019-07-25,"[Sci-Fi & Fantasy, Action & Adventure]"